"""Add content column to email_attachments

Revision ID: 15f606a6063c
Revises: d3cb32805a1e
Create Date: 2025-07-09 12:13:16.759599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15f606a6063c'
down_revision: Union[str, None] = 'd3cb32805a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add content column to store attachment data
    op.add_column('email_attachments', sa.Column('content', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove content column
    op.drop_column('email_attachments', 'content')
    # ### end Alembic commands ###
